parameters:
#    kayo_crud.example.class: Kayo\Bundle\CrudBundle\Example

services:
#    kayo_crud.example:
#        class: %kayo_crud.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
